In [15]:
# Import Tensorflow
import tensorflow as tf
import numpy as np

In [3]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# check number of dimensions of a tensor
# check ndim stands for number of dimensions
scalar.ndim

0

In [5]:
# create a vector (more than 0 dimensions)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
# Check the number of dimensions of our vector tensor
vector.ndim

1

In [7]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
[7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [9]:
# Tensorflow creates tensors with either an int32 or float32 datatype
# higher the number, more space it takes up on your computer
# Create another matrix and define the datatype

matrix_a = tf.constant([[10,7],
[3,2],
[8,9]], dtype=tf.float16) # specify datatype with "dtype"
matrix_a

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
matrix_a.ndim

2

In [11]:
# tensor has more than 2 dimensions
ten = tf.constant([[[1,2,3],
[4,5,6]],
[[7,8,9],
[10,11,12]],
[[13, 14, 15],
[16,17,18]]]
)
ten

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [12]:
ten.ndim

3

In [13]:
# We can also create tensors with tf.Variable except these tensors can now be change 
changeable_tensor = tf.Variable([10, 7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>

In [16]:
# Create tensor from nump array
J = tf.constant(np.array([3,7,10]))
J


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 3,  7, 10])>

In [17]:
# Convert tensor to numpy array
np.array(J), type(np.array(J))

(array([ 3,  7, 10]), numpy.ndarray)

In [18]:
# check if you've got access to GPU
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [19]:
# find information about your GPU using...
!nvidia-smi

Tue Apr 12 00:44:09 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 462.13       Driver Version: 462.13       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 307... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   51C    P8    12W /  N/A |   6019MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [20]:
#Create 5 dimension tensor of 50 numbers between 0 and 100
G = tf.constant(np.random.randint(0, 100, 50), shape=(1,1,1,1, 50))
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [21]:
#If you need to remove single-dimensions from a tensor..
# Squeeze tensor G (remove all 1 dimensions)
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)